services:
  esoft_db:
    image: 'mysql:9.3.0'
    environment:
      - 'MYSQL_DATABASE=esoft_db'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
